import * as color from './blocks/test-color';
import * as fonts from './blocks/test-fonts.js';
import * as gradientBg from './blocks/test-gradient-bg.js';
import * as manual from './blocks/test-manual.js';
import * as marginPadding from './blocks/test-margin-padding';
import * as marginPaddingDevices from './blocks/test-margin-padding-devices';
import * as normalBg from './blocks/test-normal-bg.js';
import * as styling from './blocks/test-styling.js';
import * as typography from './blocks/test-typography.js';
